"""Added category column to inductees table

Revision ID: 226ad5246bcd
Revises: 
Create Date: 2024-11-12 15:31:49.088117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226ad5246bcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inductees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inductees', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
